name = "the-encoders-club"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "encoders-club-db"
database_id = "62dd94a6-0e03-42fc-ba20-60e5726bf572"

# Assets
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Site configuration
[site]
bucket = ".open-next/assets"
